// examples/1.frameworks/nextjs/components/Alert.tsx
import type { ReactNode } from 'react'

const styles = {
  info: 'bg-blue-50 border-blue-400 text-blue-900 dark:bg-blue-950/50 dark:border-blue-500/50 dark:text-blue-200',
  warning:
    'bg-amber-50 border-amber-400 text-amber-900 dark:bg-amber-950/50 dark:border-amber-500/50 dark:text-amber-200',
  success:
    'bg-emerald-50 border-emerald-400 text-emerald-900 dark:bg-emerald-950/50 dark:border-emerald-500/50 dark:text-emerald-200',
  danger: 'bg-red-50 border-red-400 text-red-900 dark:bg-red-950/50 dark:border-red-500/50 dark:text-red-200',
}

export default function Alert({
  type = 'info',
  children,
}: {
  type?: 'info' | 'warning' | 'success' | 'danger'
  children?: ReactNode
}) {
  return (
    <div
      className={`my-4 rounded-lg border-l-4 px-4 py-3 text-sm leading-relaxed ${styles[type]}`}
      role="alert"
    >
      {children}
    </div>
  )
}

// examples/4.ai/nuxt-ai-sdk/app/components/Alert.vue
<script setup lang="ts">
defineProps<{
  type?: 'info' | 'warning' | 'success' | 'error'
}>()

const colors: Record<string, string> = {
  info: 'bg-blue-50 border-blue-200 text-blue-900 dark:bg-blue-950 dark:border-blue-800 dark:text-blue-100',
  warning:
    'bg-yellow-50 border-yellow-200 text-yellow-900 dark:bg-yellow-950 dark:border-yellow-800 dark:text-yellow-100',
  success: 'bg-green-50 border-green-200 text-green-900 dark:bg-green-950 dark:border-green-800 dark:text-green-100',
  error: 'bg-red-50 border-red-200 text-red-900 dark:bg-red-950 dark:border-red-800 dark:text-red-100',
}
</script>

<template>
  <div
    class="my-3 rounded-lg border p-4 text-sm"
    :class="colors[type ?? 'info']"
  >
    <slot />
  </div>
</template>
