// examples/2.vite/react/src/App.tsx
import { ComarkClient } from '@comark/react/components/ComarkClient'
import Alert from './components/Alert'
import Live from './Live'

const markdown = `
# Hello *World*

::alert{type="info"}
This is an alert!
::
`

export default function App() {
  return (
    <>
      <ComarkClient components={{ Alert }}>{markdown}</ComarkClient>
      <hr className="my-8" />
      <Live />
    </>
  )
}

// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { Comark } from 'comark/vue'
import Alert from './components/Alert.vue'

const markdown = `
# Hello *World*

::alert{type="info"}
This is an alert!
::
`
</script>

<template>
  <Suspense>
    <Comark
      :components="{ Alert }"
    >
      {{ markdown }}
    </Comark>
  </Suspense>
</template>
