// packages/comark-svelte/src/components/Binding.svelte
<!--
@component
Renders a `{{ path || default }}` binding from the `binding` plugin as plain
text. Receives the resolved `value` prop (looked up against the ambient
render context via the `:value` dot-path) and a `defaultValue` fallback.

@example
```svelte
<script>
  import binding, { Binding } from '@comark/svelte/plugins/binding'
  import { Comark } from '@comark/svelte'

  const data = { user: { name: 'Ada' } }
</script>

<Comark
  markdown="Hello {{ data.user.name || guest }}!"
  plugins={[binding()]}
  components={{ Binding }}
  {data}
/>
```
-->
<script lang="ts">
  let {
    value,
    defaultValue,
  }: {
    value?: unknown
    defaultValue?: string
  } = $props()

  let rendered = $derived(
    value !== undefined && value !== null
      ? String(value)
      : (defaultValue ?? ''),
  )
</script>

{rendered}

// packages/comark-react/src/components/Binding.tsx
import type React from 'react'

export interface BindingProps {
  /**
   * Resolved value for the binding, injected by the Comark renderer after
   * looking up the `:value` dot-path against the ambient render context.
   */
  value?: unknown
  /**
   * Fallback rendered when `value` is `undefined` or `null`.
   */
  defaultValue?: string
}

/**
 * Renders a `{{ path || default }}` binding as plain text.
 *
 * Pair with the `binding` plugin and wire via `components={{ binding: Binding }}`.
 */
export function Binding({ value, defaultValue }: BindingProps): React.ReactNode {
  if (value !== undefined && value !== null) return String(value)
  return defaultValue ?? ''
}
