// packages/comark-angular/plugins/binding/binding.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  Renderer2,
  OnChanges,
  SimpleChanges,
  inject,
  input,
} from '@angular/core'

/**
 * Renders a `{{ path || default }}` binding as plain text.
 *
 * Pair with the `binding` plugin and wire via `components: { binding: BindingComponent }`.
 */
@Component({
  selector: 'comark-binding',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '',
})
export class Binding implements OnChanges {
  /**
   * Resolved value for the binding, injected by the Comark renderer after
   * looking up the `:value` dot-path against the ambient render context.
   */
  readonly value = input<unknown>()

  /**
   * Fallback rendered when `value` is `undefined` or `null`.
   */
  readonly defaultValue = input<string>()

  private elementRef = inject(ElementRef)
  private renderer = inject(Renderer2)

  ngOnChanges(_changes: SimpleChanges): void {
    const hostEl = this.elementRef.nativeElement as HTMLElement
    while (hostEl.firstChild) {
      hostEl.removeChild(hostEl.firstChild)
    }

    const text = this.value() !== undefined && this.value() !== null ? String(this.value()) : (this.defaultValue() ?? '')

    const textNode = this.renderer.createText(text)
    this.renderer.appendChild(hostEl, textNode)
  }
}

// packages/comark-react/src/components/Binding.tsx
import type React from 'react'

export interface BindingProps {
  /**
   * Resolved value for the binding, injected by the Comark renderer after
   * looking up the `:value` dot-path against the ambient render context.
   */
  value?: unknown
  /**
   * Fallback rendered when `value` is `undefined` or `null`.
   */
  defaultValue?: string
}

/**
 * Renders a `{{ path || default }}` binding as plain text.
 *
 * Pair with the `binding` plugin and wire via `components={{ binding: Binding }}`.
 */
export function Binding({ value, defaultValue }: BindingProps): React.ReactNode {
  if (value !== undefined && value !== null) return String(value)
  return defaultValue ?? ''
}
