// packages/comark-angular/src/components/comark.component.ts
import {
  Component,
  Input,
  OnChanges,
  SimpleChanges,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Type,
} from '@angular/core'
import { createSerializedParse } from 'comark'
import type { ParseOptions, ComarkTree } from 'comark'
import { ComarkRendererComponent } from './comark-renderer.component.ts'

/**
 * High-level Comark component that accepts raw markdown, parses it,
 * and renders the resulting AST.
 *
 * @example
 * ```html
 * <comark [markdown]="content" [components]="customComponents" />
 * ```
 */
@Component({
  selector: 'comark',
  standalone: true,
  imports: [ComarkRendererComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (tree) {
      <comark-renderer
        [tree]="tree"
        [components]="components"
        [streaming]="streaming"
        [caret]="caret"
        [data]="data"
      />
    }
  `,
})
export class ComarkComponent implements OnChanges {
  /** The markdown content to parse and render */
  @Input() markdown: string = ''

  /** Parser options (excluding plugins) */
  @Input() options: Exclude<ParseOptions, 'plugins'> = {}

  /** Additional plugins to use */
  @Input() plugins: ParseOptions['plugins'] = []

  /**
   * Strip wrapper tags from the top level of the tree — shorthand for
   * `options.unwrap`. `true` unwraps `<p>`; a space-separated string or array
   * unwraps the listed tags.
   */
  @Input() unwrap: boolean | string | string[] = false

  /** Custom component mappings for element tags */
  @Input() components: Record<string, Type<any>> = {}

  /** Enable streaming mode */
  @Input() streaming: boolean = false

  /** If document has a <!-- more --> comment, only render content before it */
  @Input() summary: boolean = false

  /** Append a caret to the last text node (for streaming UIs) */
  @Input() caret: boolean | { class: string } = false

  /** Additional data to pass to the renderer for :binding resolution */
  @Input() data: Record<string, unknown> = {}

  tree: ComarkTree | null = null

  private serializedParse = createSerializedParse({})

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['options'] || changes['plugins'] || changes['unwrap']) {
      this.serializedParse = createSerializedParse({
        ...this.options,
        ...(this.unwrap ? { unwrap: this.unwrap } : {}),
        plugins: this.plugins,
      })
    }
    if (
      changes['markdown'] ||
      changes['options'] ||
      changes['plugins'] ||
      changes['unwrap'] ||
      changes['streaming'] ||
      changes['summary']
    ) {
      this.parseMarkdown()
    }
  }

  private parseMarkdown(): void {
    let source = this.markdown || ''
    if (this.summary) {
      source = source.split('<!-- more -->')[0] || ''
    }
    source = source.trim()

    this.serializedParse(source, { streaming: this.streaming }).then((result) => {
      this.tree = result
      this.cdr.markForCheck()
    })
  }
}

// packages/comark-react/src/components/Comark.tsx
import React from 'react'
import { parse } from 'comark'
import type { ParseOptions } from 'comark'
import { ComarkRenderer } from './ComarkRenderer.tsx'
import { ComarkClient } from './ComarkClient.tsx'

export interface ComarkProps {
  /**
   * The children content to parse and render
   */
  children?: React.ReactNode

  /**
   * The markdown content to parse and render
   */
  markdown?: string

  /**
   * Parser options (excluding plugins)
   */
  options?: Exclude<ParseOptions, 'plugins'>

  /**
   * Additional plugins to use
   */
  plugins?: ParseOptions['plugins']

  /**
   * Custom component mappings for element tags
   * Key: tag name (e.g., 'h1', 'p', 'MyComponent')
   * Value: React component
   */
  components?: Record<string, React.ComponentType<any>>

  /**
   * Dynamic component resolver function
   * Used to resolve components that aren't in the components map
   */
  componentsManifest?: (name: string) => Promise<{ default: React.ComponentType<any> }>

  /**
   * Strip wrapper tags from the top level of the tree — shorthand for
   * `options.unwrap`. `true` unwraps `<p>` (single-line rendering); a
   * space-separated string or array unwraps the listed tags. Useful for inline
   * usage like `<button><Comark markdown={text} unwrap /></button>`.
   */
  unwrap?: boolean | string | string[]

  /**
   * Enable streaming mode — delegates to ComarkClient for client-side re-rendering
   * when the markdown prop changes. Use this for LLM streaming output.
   */
  streaming?: boolean

  /**
   * If caret is true, a caret will be appended to the last text node in the tree
   * If caret is an object, it will be appended to the last text node in the tree with the given class
   */
  caret?: boolean | { class: string }

  /**
   * Additional data to pass to the renderer — referenced from markdown
   * via `:`-prefixed props using dot paths (e.g. `:foo="data.user.name"`).
   */
  data?: Record<string, unknown>

  /**
   * Additional className for the wrapper div
   */
  className?: string
}

/**
 * Comark component
 *
 * Async server component that parses markdown on the server and renders it.
 * When `streaming` is true, delegates to ComarkClient for client-side re-rendering.
 *
 * @example
 * ```tsx
 * import { Comark } from '@comark/react'
 * import CustomHeading from './CustomHeading'
 *
 * const customComponents = {
 *   h1: CustomHeading,
 *   alert: AlertComponent,
 * }
 *
 * export default function App() {
 *   const content = `
 *     # Hello World
 *
 *     This is a **markdown** document with *Comark* components.
 *
 *     ::alert{type="info"}
 *     This is an alert component
 *     ::
 *   `
 *
 *   return <Comark markdown={content} components={customComponents} />
 * }
 * ```
 */
export async function Comark({
  children,
  markdown = '',
  options = {},
  plugins = [],
  unwrap = false,
  components: customComponents = {},
  componentsManifest,
  streaming = false,
  caret = false,
  data,
  className,
}: ComarkProps) {
  const source = children ? String(children) : markdown
  // `unwrap` prop is a shorthand for the `unwrap` parse option; an explicit
  // `options.unwrap` still wins when the prop is left at its default.
  const parseOptions = unwrap ? { ...options, unwrap } : options

  if (streaming) {
    return (
      <ComarkClient
        markdown={source}
        options={parseOptions}
        plugins={plugins}
        components={customComponents}
        componentsManifest={componentsManifest}
        streaming={streaming}
        caret={caret}
        data={data}
        className={className}
      />
    )
  }

  const parsed = await parse(source, { ...parseOptions, plugins })

  return (
    <ComarkRenderer
      tree={parsed}
      components={customComponents}
      componentsManifest={componentsManifest}
      streaming={streaming}
      className={className}
      caret={caret}
      data={data}
    />
  )
}
