// packages/comark-svelte/src/components/If.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { resolveIfWrapper, shouldRenderIf, type IfProps } from 'comark/plugins/binding'

  let {
    children,
    else: elseContent,
    ...props
  }: IfProps & {
    children?: Snippet
    else?: Snippet
  } = $props()

  let visible = $derived(shouldRenderIf(props))
  let branch = $derived(visible ? children : elseContent)
  let wrapper = $derived(visible || elseContent ? resolveIfWrapper(props.as) : undefined)
</script>

{#if visible || elseContent}
  {#if wrapper}
    <svelte:element this={wrapper}>
      {@render branch?.()}
    </svelte:element>
  {:else}
    {@render branch?.()}
  {/if}
{/if}

// packages/comark-react/src/components/If.tsx
import { createElement, type ReactNode } from 'react'
import { resolveIfWrapper, shouldRenderIf, type IfProps } from 'comark/plugins/binding'

export interface IfComponentProps extends IfProps {
  children?: ReactNode
  slotElse?: ReactNode
}

/** Render the default or else slot according to the resolved props. */
export function If({ children, slotElse, ...props }: IfComponentProps): ReactNode {
  const matches = shouldRenderIf(props)
  if (!matches && slotElse === undefined) return null
  const branch = matches ? children : slotElse

  const wrapper = resolveIfWrapper(props.as)
  return wrapper ? createElement(wrapper, null, branch) : branch
}
