// examples/1.frameworks/nextjs/app/blog/[slug]/page.tsx
import type { Metadata } from 'next'
import Link from 'next/link'
import { MarkdownDocument } from '@comark/react'
import { getAllPosts, getPost } from '@/lib/posts'
import Alert from '@/components/Alert'
import FeatureCard from '@/components/FeatureCard'

export async function generateStaticParams() {
  const posts = await getAllPosts()
  return posts.map((post) => ({ slug: post.slug }))
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const post = await getPost(slug)
  return {
    title: post.title,
    description: post.description,
  }
}

export default async function BlogPost({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const post = await getPost(slug)

  return (
    <article>
      <header className="pb-4 mb-8">
        <Link
          href="/"
          className="text-sm text-neutral-500 dark:text-neutral-400 hover:text-neutral-700 dark:hover:text-neutral-300 mb-4 inline-block"
        >
          &larr; Back to all posts
        </Link>
        <h1 className="text-3xl font-bold mb-2">{post.title}</h1>
        <div className="flex items-center gap-3 text-sm text-neutral-500 dark:text-neutral-400">
          <time dateTime={post.pubDate.toISOString()}>
            {post.pubDate.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </time>
          <div className="flex gap-1.5">
            {post.tags.map((tag) => (
              <span
                key={tag}
                className="bg-neutral-200 dark:bg-neutral-800 px-2 py-0.5 rounded-full text-xs"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
      </header>
      <MarkdownDocument
        value={post.tree}
        className="prose"
        components={{ Alert, FeatureCard }}
      />
    </article>
  )
}

// examples/1.frameworks/nuxt/app/pages/blog/[slug].vue
<script setup lang="ts">
const route = useRoute()
const { data: post } = await useFetch(`/api/posts/${route.params.slug}`)

useSeoMeta({
  title: () => post.value?.title,
  description: () => post.value?.description,
})
</script>

<template>
  <article v-if="post">
    <header class="pb-4 mb-8">
      <NuxtLink
        to="/"
        class="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 mb-4 inline-block no-underline"
      >
        &larr; Back to all posts
      </NuxtLink>
      <h1 class="text-3xl font-bold mb-2">
        {{ post.title }}
      </h1>
      <div class="flex items-center gap-3 text-sm text-gray-500 dark:text-gray-400">
        <time :datetime="post.pubDate">
          {{ new Date(post.pubDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) }}
        </time>
        <div class="flex gap-1.5">
          <UBadge
            v-for="tag in post.tags"
            :key="tag"
            :label="tag"
            color="neutral"
            variant="subtle"
            size="xs"
          />
        </div>
      </div>
    </header>
    <MarkdownDocument :value="post.tree" />
  </article>
</template>
