// examples/2.vite/angular/src/app/pages/syntax.component.ts
import { Component } from '@angular/core'
import { Markdown } from '@comark/angular'
import shiki from 'comark/plugins/shiki'
import alert from 'comark/plugins/alert'
import binding, { Binding } from '@comark/angular/plugins/binding'
import { AlertComponent } from '../components/alert.component'
import { FeatureCardComponent } from '../components/feature-card.component'
import python from '@shikijs/langs/python'

@Component({
  selector: 'app-syntax',
  standalone: true,
  imports: [Markdown],
  template: `
    <comark-markdown
      [value]="markdown"
      [plugins]="plugins"
      [components]="components"
      [data]="modelData"
    />
  `,
})
export class SyntaxComponent {
  components = { alert: AlertComponent, 'feature-card': FeatureCardComponent, Binding }
  plugins = [
    shiki({
      languages: [python],
    }),
    alert(),
    binding(),
  ]
  modelData = { name: 'Ada', active: true }

  markdown = `
# Comark Syntax Showcase

All syntax features supported by Comark, from standard **CommonMark** to Comark-specific extensions.

---

## Headings

# Heading 1
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5
###### Heading 6

---

## Text Formatting

**Bold** and __also bold__

*Italic* and _also italic_

***Bold and italic*** together

~~Strikethrough~~

\`Inline code\`

---

## Links

A [plain link](https://comark.dev), a [link with title](https://comark.dev "Comark"), and a [link with attributes](https://comark.dev){target="_blank" rel="noopener"}.

---

## Lists

### Unordered

- Item one
- Item two
  - Nested item
  - Another nested item
    - Deep nested
- Item three

### Ordered

1. First item
2. Second item
   1. Nested ordered
   2. Another nested
3. Third item

### Task list

- [x] Completed task
- [ ] Pending task
- [x] Another done
- [ ] Yet to do

---

## Blockquotes

> A simple blockquote.

> Blockquotes support **formatting** and
> can span multiple lines.
>
> > Nested blockquotes work too.

---

## Alert Blockquotes

> [!NOTE]
> A note for the reader.

> [!TIP]
> A helpful tip.

> [!WARNING]
> Something to be cautious about.

> [!CAUTION]
> A potential risk or danger.

---

## Code Blocks

Plain fenced block:

~~~
No syntax highlighting
~~~

With a language:

~~~javascript
function greet(name) {
  return \`Hello, \${name}!\`
}
~~~

With a filename:

~~~typescript [utils.ts]
export function add(a: number, b: number): number {
  return a + b
}
~~~

With line highlighting:

~~~python {1,3-5}
print("Line 1 — highlighted")
print("Line 2 — not highlighted")
print("Line 3 — highlighted")
print("Line 4 — highlighted")
print("Line 5 — highlighted")
~~~

---

## Tables

| Name           | Type       | Required | Description              |
| :------------- | :--------: | :------: | -----------------------: |
| \`markdown\`     | \`string\`   | Yes      | Content to render        |
| \`options\`      | \`object\`   | No       | Parser options           |
| \`components\`   | \`object\`   | No       | Custom component map     |

---

## Block Components

Block components are declared with \`::name\` and closed with \`::\`.
Props can be passed inline or as YAML frontmatter.

### Inline props

::alert{type="info"}
This is an **info** alert rendered with a custom \`AlertComponent\`.
::

::alert{type="warning"}
This is a **warning** alert with a [link](https://comark.dev).
::

::alert{type="success"}
Task completed successfully.
::

::alert{type="error"}
Something went wrong.
::

### YAML frontmatter props

::alert
---
type: warning
---
This alert uses **YAML frontmatter** for its \`type\` prop.
::

---

## Component Slots

Angular components receive default content via \`<ng-content />\`, and named slots via \`<ng-content select="[slot=name]" />\`:

::feature-card
#header
Slot-aware Angular component

#default
This body is the default slot. It can contain **Markdown**, links, lists, or any nested Comark content.

#footer
Rendered through the \`footer\` slot in \`FeatureCardComponent\`.
::

---

## Nested Block Components

Increase fence depth with extra colons (\`:::\`, \`::::\`, …) to nest:

::alert{type="info"}
Outer info alert.
  :::alert{type="warning"}
  Nested warning inside the info.
  :::
::

---

## Inline Components

Inline components are prefixed with a single colon.

Plain: :span

With label: :span[hello]

With props: :span[hello]{style="color: tomato;"}

---

## Two-way model binding

Native form elements with \`::prop="path"\` write back to the document model. Change a field and watch the bound text update.

**Name:** {{ data.name }}

:input{::value="data.name" type="text"}

**Active:** {{ data.active }}

:input{::checked="data.active" type="checkbox"}

---

## Frontmatter

Documents can declare YAML frontmatter at the top (before any content):

~~~yaml
---
title: My Document
description: A short description
tags:
  - markdown
  - comark
published: true
---
~~~

Access frontmatter via \`tree.frontmatter\` when using the \`MarkdownDocument\` component.

---

## Comments

HTML comments are parsed and ignored by the renderer:

<!-- This comment is invisible in the output -->

Text before the comment and text after the comment both render normally.
`
}

// examples/2.vite/vue/src/pages/syntax.vue
<script setup lang="ts">
import { Markdown } from '@comark/vue'
import shiki from '@comark/vue/plugins/shiki'
import binding, { Binding } from '@comark/vue/plugins/binding'
import Alert from '@/components/Alert.vue'
import ProseUnwrapDiv from '@/components/prose/ProseUnwrapDiv.vue'
import python from '@shikijs/langs/python'

const modelData = { name: 'Ada', active: true }

const markdown = `
# Comark Syntax Showcase

All syntax features supported by Comark, from standard **CommonMark** to Comark-specific extensions.

---

## Headings

# Heading 1
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5
###### Heading 6

---

## Text Formatting

**Bold** and __also bold__

*Italic* and _also italic_

***Bold and italic*** together

~~Strikethrough~~

\`Inline code\`

---

## Links

A [plain link](https://comark.dev), a [link with title](https://comark.dev "Comark"), and a [link with attributes](https://comark.dev){target="_blank" rel="noopener"}.

---

## Lists

### Unordered

- Item one
- Item two
  - Nested item
  - Another nested item
    - Deep nested
- Item three

### Ordered

1. First item
2. Second item
   1. Nested ordered
   2. Another nested
3. Third item

### Task list

- [x] Completed task
- [ ] Pending task
- [x] Another done
- [ ] Yet to do

---

## Blockquotes

> A simple blockquote.

> Blockquotes support **formatting** and
> can span multiple lines.
>
> > Nested blockquotes work too.

---

## Alert Blockquotes

> [!NOTE]
> A note for the reader.

> [!TIP]
> A helpful tip.

> [!WARNING]
> Something to be cautious about.

> [!CAUTION]
> A potential risk or danger.

---

## Code Blocks

Plain fenced block:

~~~
No syntax highlighting
~~~

With a language:

~~~javascript
function greet(name) {
  return \`Hello, \${name}!\`
}
~~~

With a filename:

~~~typescript [utils.ts]
export function add(a: number, b: number): number {
  return a + b
}
~~~

With line highlighting:

~~~python {1,3-5}
print("Line 1 — highlighted")
print("Line 2 — not highlighted")
print("Line 3 — highlighted")
print("Line 4 — highlighted")
print("Line 5 — highlighted")
~~~

---

## Tables

| Name           | Type       | Required | Description              |
| :------------- | :--------: | :------: | -----------------------: |
| \`markdown\`     | \`string\`   | Yes      | Content to render        |
| \`options\`      | \`object\`   | No       | Parser options           |
| \`components\`   | \`object\`   | No       | Custom component map     |

---

## Span Attributes

Apply classes and attributes to any inline content:

[Highlighted span]{.bg-yellow-200 .dark:bg-yellow-900 .px-1 .rounded}

[Custom styled span]{style="color: steelblue; font-weight: 600;"}

Bold with class: **Important notice**{.text-red-500}

Link with attributes: [Open in new tab](https://comark.dev){target="_blank" .underline}

---

## Block Components

Block components are declared with \`::name\` and closed with \`::\`.
Props can be passed inline or as YAML frontmatter.

### Inline props

::alert{type="info"}
This is an **info** alert rendered with a custom \`Alert\` component.
::

::alert{type="warning"}
This is a **warning** alert with a [link](https://comark.dev).
::

::alert{type="success"}
Task completed successfully.
::

::alert{type="danger"}
Something went wrong.
::

### YAML frontmatter props

::alert
---
type: warning
---
This alert uses **YAML frontmatter** for its \`type\` prop.
::

---

## Nested Block Components

Increase fence depth with extra colons (\`:::\`, \`::::\`, …) to nest:

::alert{type="info"}
Outer info alert.
  :::alert{type="warning"}
  Nested warning inside the info.
  :::
::

---

## Block Components with Named Slots

Named slots use the \`#slot-name\` syntax inside a component block.

::alert{type="info"}
This is the default slot content.
::

---

## Inline Components

Inline components are prefixed with a single colon.

Plain: :span

With label: :span[hello]

With props: :span[hello]{style="color: tomato;"}

---

## Slot Unwrap — \`<slot unwrap="div" />\`

\`ProseUnwrapDiv\` renders \`<slot unwrap="div" />\`.
The wrapping \`div\` is stripped, and its children are rendered directly:

::prose-unwrap-div
:::div{style="border: 1px dashed currentColor; padding: 0.5rem; border-radius: 4px;"}
This content is inside a \`div\` with inline styles — but the \`div\` itself is removed by the unwrap slot.
:::
::

---

## Two-way model binding

Native form elements with \`::prop="path"\` write back to the document model. Change a field and watch the bound text update.

**Name:** {{ data.name }}

:input{::value="data.name" type="text"}

**Active:** {{ data.active }}

:input{::checked="data.active" type="checkbox"}

---

## Frontmatter

Documents can declare YAML frontmatter at the top (before any content):

~~~yaml
---
title: My Document
description: A short description
tags:
  - markdown
  - comark
published: true
---
~~~

Access frontmatter via \`tree.frontmatter\` when using the \`MarkdownDocument\` component.

---

## Comments

HTML comments are parsed and ignored by the renderer:

<!-- This comment is invisible in the output -->

Text before the comment and text after the comment both render normally.
`
</script>

<template>
  <Markdown
    :plugins="[
      shiki({
        languages: [python],
      }),
      binding(),
    ]"
    :value="markdown"
    :components="{ Alert, ProseUnwrapDiv, Binding }"
    :data="modelData"
  />
</template>
