// packages/comark-angular/src/components/comark-renderer.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges,
  Type,
  inject,
} from '@angular/core'
import {
  subscribeComarkDocument,
  type ComarkDocumentSubscription,
  type ComarkElement,
  type ComarkNode,
  type ComarkTree,
  type NodeRenderData,
} from 'comark'
import { ComarkNodeComponent } from './comark-node.component.ts'
import { findLastTextNodeAndAppendNode, getCaret } from '../utils/caret.ts'

/**
 * ComarkRenderer component
 *
 * Renders a pre-parsed Comark tree to Angular components/HTML.
 * Supports custom component mapping for element tags.
 *
 * @example
 * ```html
 * <comark-renderer [tree]="parsedTree" [components]="customComponents" />
 * ```
 */
@Component({
  selector: 'comark-renderer',
  standalone: true,
  imports: [ComarkNodeComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="comark-content">
      @for (node of renderedNodes; track $index) {
        <comark-node
          [node]="node"
          [components]="components"
          [renderData]="renderData"
        />
      }
    </div>
  `,
})
export class ComarkRendererComponent implements OnInit, OnChanges, OnDestroy {
  /** The Comark tree to render */
  @Input({ required: true }) tree!: ComarkTree

  /** Custom component mappings for element tags */
  @Input() components: Record<string, Type<any>> = {}

  /** Enable streaming mode */
  @Input() streaming: boolean = false

  /** Append a caret to the last text node (for streaming UIs) */
  @Input() caret: boolean | { class: string } = false

  /** Additional data to pass to the renderer for :binding resolution */
  @Input() data: Record<string, unknown> = {}

  /**
   * Document key used to subscribe to live updates via `globalThis.comarkContext`.
   * Falls back to the tree's own `meta.key` when set by a plugin.
   * When a context exists but no key is provided, an auto id is allocated so the
   * instance still appears in Vite DevTools.
   */
  @Input() comarkKey?: string

  private cdr = inject(ChangeDetectorRef)
  private liveTree: ComarkTree | null = null
  private subscription: ComarkDocumentSubscription | null = null

  // Live document support via ambient context (auto-id when DevTools is present).
  ngOnInit(): void {
    this.subscription = subscribeComarkDocument(this.tree, this.comarkKey, (tree) => {
      this.liveTree = tree
      this.cdr.markForCheck()
    })
  }

  ngOnChanges(changes: SimpleChanges): void {
    // Keep the context document in sync when the parent re-parses.
    if (changes['tree'] && !changes['tree'].firstChange) {
      this.subscription?.set(this.tree)
    }
  }

  ngOnDestroy(): void {
    this.subscription?.cleanup(true)
    this.subscription = null
  }

  private get activeTree(): ComarkTree {
    return this.liveTree ?? this.tree
  }

  get renderedNodes(): ComarkNode[] {
    const nodes = [...(this.activeTree.nodes || [])]
    const caretNode = getCaret(this.caret)

    if (this.streaming && caretNode && nodes.length > 0) {
      const hasStreamCaret = findLastTextNodeAndAppendNode(nodes[nodes.length - 1] as ComarkElement, caretNode)
      if (!hasStreamCaret) {
        nodes.push(caretNode)
      }
    }

    return nodes
  }

  get renderData(): NodeRenderData {
    return {
      frontmatter: this.activeTree.frontmatter,
      meta: this.activeTree.meta,
      data: this.data || {},
      props: {},
    }
  }
}

// packages/comark-svelte/src/components/ComarkRenderer.svelte
<!--
@component
Renders a Comark AST tree to Svelte components/HTML.

Accepts a parsed `ComarkTree` and renders each top-level node via `ComarkNode`.
Supports custom component mappings and a streaming caret indicator.

@example
```svelte
<script>
  import { ComarkRenderer } from '@comark/svelte'
  import { parse } from 'comark'

  const tree = await parse('# Hello **World**')
</script>

<ComarkRenderer {tree} />
```
-->
<script lang="ts">
  import { untrack } from 'svelte'
  import {
    subscribeComarkDocument,
    type ComarkDocumentSubscription,
    type ComarkTree,
    type ComponentManifest,
  } from 'comark'
  import type { ComponentResolver } from '../types.js'
  import ComarkNode from './ComarkNode.svelte'

  let {
    tree,
    components = {},
    componentsManifest,
    resolver,
    streaming = false,
    caret: caretProp = false,
    data,
    class: className = '',
    comarkKey,
  }: {
    tree: ComarkTree | { nodes: ComarkTree['nodes'] }
    components?: Record<string, any>
    componentsManifest?: ComponentManifest
    resolver?: ComponentResolver
    streaming?: boolean
    caret?: boolean | { class: string }
    data?: Record<string, unknown>
    class?: string
    /**
     * Document key used to subscribe to live updates via `globalThis.comarkContext`.
     * Falls back to the tree's own `meta.key` when set by a plugin.
     * When a context exists but no key is provided, an auto id is allocated so the
     * instance still appears in Vite DevTools.
     */
    comarkKey?: string
  } = $props()

  // Live document support via ambient context (auto-id when DevTools is present).
  let liveTree = $state<ComarkTree | null>(null)
  let subscription: ComarkDocumentSubscription | null = null

  $effect(() => {
    // Track key identity so we resubscribe when comarkKey / meta.key change.
    const keyHint = (tree as ComarkTree).meta?.key || comarkKey
    void keyHint
    const seed = untrack(() => tree as ComarkTree)
    subscription = subscribeComarkDocument(seed, comarkKey, (next) => (liveTree = next))
    return () => {
      subscription?.cleanup(true)
      subscription = null
    }
  })

  // Keep the context document in sync when the parent re-parses.
  // Skip the first run — subscribe already seeded the document.
  let treeSynced = false
  $effect(() => {
    const current = tree
    if (!treeSynced) {
      treeSynced = true
      return
    }
    untrack(() => subscription?.set(current as ComarkTree))
  })

  let activeTree = $derived(liveTree ?? tree)

  let caretClass = $derived(
    streaming && caretProp
      ? (typeof caretProp === 'object' && caretProp.class) || ''
      : null,
  )

  let renderData = $derived({
    frontmatter:
      (activeTree as ComarkTree).frontmatter || (activeTree as unknown as { data: Record<string, unknown> }).data || {},
    meta: (activeTree as ComarkTree).meta || {},
    data: data || {},
    props: {},
  })
</script>

<div class="comark-content {className}">
  {#each activeTree.nodes as node, i (i)}
    <ComarkNode
      {node}
      {components}
      {componentsManifest}
      {resolver}
      caretClass={i === activeTree.nodes.length - 1 ? caretClass : null}
      {renderData}
    />
  {/each}
</div>
