// packages/comark-react/src/components/Math.tsx
import { useState, useEffect } from 'react'
import katex from 'katex'

export interface MathProps {
  content: string
  className?: string
}

export function Math({ content, className = '' }: MathProps) {
  const isInline = className.includes('inline')
  const [mathml, setMathml] = useState<string>('...')

  useEffect(() => {
    try {
      const rendered = katex.renderToString(content, {
        throwOnError: true,
        displayMode: !isInline,
      })
      setMathml(rendered)
    } catch {
      // Keep loading state on error
    }
  }, [content, isInline])

  if (isInline) {
    return (
      <span
        className="math inline"
        dangerouslySetInnerHTML={{ __html: mathml }}
      />
    )
  }

  return (
    <div
      className="math block"
      dangerouslySetInnerHTML={{ __html: mathml }}
    />
  )
}

// packages/comark-svelte/src/components/Math.svelte
<!--
@component
Renders a KaTeX math expression from a Comark AST `math` node.

Receives a `content` prop with the LaTeX source and a `class` prop that
determines inline vs display mode (display when class does NOT contain "inline").

@example
```svelte
<script>
  import math, { Math } from '@comark/svelte/plugins/math'
  import { Markdown } from '@comark/svelte'
</script>

<Markdown value="$E = mc^2$" plugins={[math()]} components={{ math: Math }} />
```
-->
<script lang="ts">
  import katex from 'katex'

  let {
    content,
    class: className = '',
  }: {
    content: string
    class?: string
  } = $props()

  let isInline = $derived(className.split(' ').includes('inline'))

  let mathml = $derived.by(() => {
    try {
      return katex.renderToString(content, {
        throwOnError: true,
        displayMode: !isInline,
      })
    }
    catch {
      return '...'
    }
  })
</script>

<!-- eslint-disable svelte/no-at-html-tags -- KaTeX output is safe rendered HTML -->
{#if isInline}
  <span class="math inline">{@html mathml}</span>
{:else}
  <div class="math block">{@html mathml}</div>
{/if}
