// packages/comark-react/src/components/Mermaid.tsx
import { useState, useEffect } from 'react'
import { renderMermaidSVG, THEMES, type DiagramColors } from 'beautiful-mermaid'
import type { ThemeNames } from 'comark/plugins/mermaid'

export interface MermaidProps {
  content: string
  class?: string
  height?: string
  width?: string
  theme?: ThemeNames | DiagramColors
  themeDark?: ThemeNames | DiagramColors
}

export function Mermaid({
  content,
  class: className = '',
  height = 'auto',
  width = '100%',
  theme,
  themeDark,
}: MermaidProps) {
  const [svgContent, setSvgContent] = useState<string>('')
  const [error, setError] = useState<string | null>(null)
  const [isDark, setIsDark] = useState(false)

  // Detect dark mode from HTML class
  useEffect(() => {
    const htmlEl = document.querySelector('html')
    if (htmlEl) {
      setIsDark(htmlEl.classList.contains('dark') || false)

      // Watch for class changes on HTML element
      const observer = new MutationObserver(() => {
        const newIsDark = htmlEl.classList.contains('dark')
        setIsDark(newIsDark)
      })

      observer.observe(htmlEl, {
        attributes: true,
        attributeFilter: ['class'],
      })

      return () => observer.disconnect()
    }
  }, [])

  // Update mermaid theme when it changes
  useEffect(() => {
    const renderDiagram = async () => {
      try {
        setError(null)

        // Determine which theme to use based on dark mode and props
        const themeProp = isDark ? themeDark : theme

        let resolvedTheme
        if (typeof themeProp === 'string') {
          resolvedTheme = THEMES[themeProp]
        }
        else if (typeof themeProp === 'object') {
          resolvedTheme = themeProp
        }

        // Fallback to default themes if no prop is set
        if (!resolvedTheme) {
          resolvedTheme = THEMES[isDark ? 'tokyo-night' : 'tokyo-light']
        }

        const svg = renderMermaidSVG(content, resolvedTheme)
        setSvgContent(svg)
      }
      catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to render diagram')
      }
    }

    renderDiagram()
  }, [content, theme, themeDark, isDark])

  return (
    <div
      className={`mermaid ${className}`}
      style={{
        display: 'flex',
        justifyContent: 'center',
        width,
        height,
      }}
      data-error={error}
      dangerouslySetInnerHTML={{ __html: svgContent }}
    />
  )
}

// packages/comark-svelte/src/components/Mermaid.svelte
<!--
@component
Renders a Mermaid diagram from a Comark AST `mermaid` node.

Receives a `content` prop with the Mermaid diagram source.
Supports `theme` and `themeDark` props for light/dark mode theming.
Automatically detects dark mode from the `<html>` element's `dark` class.

@example
```svelte
<script>
  import mermaid, { Mermaid } from '@comark/svelte/plugins/mermaid'
  import { Markdown } from '@comark/svelte'
</script>

<Markdown value={md} plugins={[mermaid()]} components={{ mermaid: Mermaid }} />
```
-->
<script lang="ts">
  import { onMount } from 'svelte'
  import {
    renderMermaidSVG,
    THEMES,
    type DiagramColors,
  } from 'beautiful-mermaid'
  import type { ThemeNames } from 'comark/plugins/mermaid'

  let {
    content,
    class: className = '',
    height = 'auto',
    width = '100%',
    theme,
    'theme-dark': themeDark,
  }: {
    'content': string
    'class'?: string
    'height'?: string
    'width'?: string
    'theme'?: ThemeNames | DiagramColors
    'theme-dark'?: ThemeNames | DiagramColors
  } = $props()

  let isDark = $state(false)

  let resolvedTheme = $derived.by(() => {
    const themeProp = isDark ? themeDark : theme

    let resolved: DiagramColors | undefined
    if (typeof themeProp === 'string') {
      resolved = THEMES[themeProp]
    }
    else if (typeof themeProp === 'object') {
      resolved = themeProp
    }

    if (!resolved) {
      resolved = THEMES[isDark ? 'tokyo-night' : 'tokyo-light']
    }

    return resolved
  })

  let { svgContent, error } = $derived.by(() => {
    try {
      return {
        svgContent: renderMermaidSVG(content, resolvedTheme),
        error: null as string | null,
      }
    }
    catch (err) {
      return {
        svgContent: '',
        error: err instanceof Error ? err.message : 'Failed to render diagram',
      }
    }
  })

  onMount(() => {
    const htmlEl = document.documentElement
    isDark = htmlEl.classList.contains('dark')

    const observer = new MutationObserver(() => {
      isDark = htmlEl.classList.contains('dark')
    })

    observer.observe(htmlEl, {
      attributes: true,
      attributeFilter: ['class'],
    })

    return () => observer.disconnect()
  })
</script>

<div
  class="mermaid {className}"
  style:display="flex"
  style:justify-content="center"
  style:width
  style:height
  data-error={error}
>
  <!-- eslint-disable svelte/no-at-html-tags -- Mermaid SVG output is safe rendered content -->
  {@html svgContent}
</div>
