// examples/2.vite/vue/src/App.vue
<template>
  <Suspense>
    <div class="min-h-screen flex flex-col">
      <header class="border-b border-gray-200 dark:border-gray-800">
        <nav class="max-w-2xl mx-auto px-6 py-4 flex items-center gap-6">
          <RouterLink
            to="/"
            class="text-lg font-semibold text-gray-900 dark:text-white no-underline"
          >
            Comark Blog
          </RouterLink>
          <RouterLink
            to="/syntax"
            class="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 no-underline"
          >
            Syntax
          </RouterLink>
          <RouterLink
            to="/live"
            class="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 no-underline"
          >
            Live
          </RouterLink>
        </nav>
      </header>
      <main class="max-w-2xl mx-auto px-6 py-8 flex-1 w-full">
        <RouterView />
      </main>
      <footer
        class="border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500 dark:text-gray-400 py-6"
      >
        Built with
        <a
          href="https://vuejs.org"
          class="text-gray-700 dark:text-gray-300 underline"
          >Vue</a
        >
        +
        <a
          href="https://ui.nuxt.com"
          class="text-gray-700 dark:text-gray-300 underline"
          >Nuxt UI</a
        >
        +
        <a
          href="https://comark.dev"
          class="text-gray-700 dark:text-gray-300 underline"
          >Comark</a
        >
      </footer>
    </div>
  </Suspense>
</template>

// examples/2.vite/angular/src/app/app.component.ts
import { Component } from '@angular/core'
import { RouterLink, RouterOutlet } from '@angular/router'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: `
    <div class="min-h-screen flex flex-col">
      <header class="border-b border-neutral-200 dark:border-neutral-800">
        <nav class="max-w-2xl mx-auto px-6 py-4 flex items-center gap-6">
          <a
            routerLink="/"
            class="text-lg font-semibold text-neutral-900 dark:text-white no-underline cursor-pointer"
          >
            Comark Blog
          </a>
          <a
            routerLink="/syntax"
            class="text-sm text-neutral-500 dark:text-neutral-400 hover:text-neutral-700 dark:hover:text-neutral-300 no-underline cursor-pointer"
          >
            Syntax
          </a>
          <a
            routerLink="/live"
            class="text-sm text-neutral-500 dark:text-neutral-400 hover:text-neutral-700 dark:hover:text-neutral-300 no-underline cursor-pointer"
          >
            Live
          </a>
        </nav>
      </header>
      <main class="max-w-2xl mx-auto px-6 py-8 flex-1 w-full prose">
        <router-outlet />
      </main>
      <footer
        class="border-t border-neutral-200 dark:border-neutral-800 text-center text-sm text-neutral-500 dark:text-neutral-400 py-6"
      >
        Built with
        <a
          href="https://angular.dev"
          class="text-neutral-700 dark:text-neutral-300 underline"
          >Angular</a
        >
        +
        <a
          href="https://comark.dev"
          class="text-neutral-700 dark:text-neutral-300 underline"
          >Comark</a
        >
      </footer>
    </div>
  `,
})
export class AppComponent {}
