// packages/comark-svelte/src/components/MarkdownParsed.svelte
<!--
@component
Renders an already-parsed Comark AST tree to Svelte components/HTML — no
parser in the client bundle.

Accepts a parsed `ComarkTree` and renders each top-level node via `MarkdownNode`.
Supports custom component mappings and a streaming caret indicator.

@example
```svelte
<script>
  import { MarkdownParsed } from '@comark/svelte'
  import { parse } from 'comark'

  const document = await parse('# Hello **World**')
</script>

<MarkdownParsed value={document} />
```
-->
<script lang="ts">
  import { untrack } from 'svelte'
  import type { ComarkTree, ComponentManifest } from 'comark'
  import type { ComponentResolver } from '../types.js'
  import MarkdownNode from './MarkdownNode.svelte'
  import { warnDeprecated } from '../internal/deprecation.js'

  let {
    value,
    tree: treeProp,
    components = {},
    componentsManifest,
    resolver,
    streaming = false,
    caret: caretProp = false,
    data,
    class: className = '',
    comarkKey,
  }: {
    value?: ComarkTree | { nodes: ComarkTree['nodes'] }
    /** @deprecated Use `value` instead */
    tree?: ComarkTree | { nodes: ComarkTree['nodes'] }
    components?: Record<string, any>
    componentsManifest?: ComponentManifest
    resolver?: ComponentResolver
    streaming?: boolean
    caret?: boolean | { class: string }
    data?: Record<string, unknown>
    class?: string
    comarkKey?: string
  } = $props()

  // svelte-ignore state_referenced_locally — deprecation check only needs the initial value
  if (treeProp !== undefined && value === undefined) {
    warnDeprecated('tree (prop)', 'value')
  }

  let tree = $derived(value ?? treeProp ?? { nodes: [] })

  // Live document support: if an ambient context exists, subscribe to updates
  // for this key and re-render with the pushed tree. Cleaned up on unmount.
  // The key is the tree's own `meta.key` (set by a plugin) or the `comarkKey` prop.
  let liveTree = $state<ComarkTree | null>(null)
  let key = $derived((tree as ComarkTree).meta?.key || comarkKey)
  $effect(() => {
    if (!key || !globalThis.comarkContext) return
    const seed = untrack(() => tree as ComarkTree)
    const cleanup = globalThis.comarkContext.get(key, seed).listen((next) => (liveTree = next))
    return () => cleanup(true)
  })

  let activeTree = $derived(liveTree ?? tree)

  let caretClass = $derived(
    streaming && caretProp
      ? (typeof caretProp === 'object' && caretProp.class) || ''
      : null,
  )

  let renderData = $derived({
    frontmatter:
      (activeTree as ComarkTree).frontmatter || (activeTree as unknown as { data: Record<string, unknown> }).data || {},
    meta: (activeTree as ComarkTree).meta || {},
    data: data || {},
    props: {},
  })
</script>

<div class="comark-content {className}">
  {#each activeTree.nodes as node, i (i)}
    <MarkdownNode
      {node}
      {components}
      {componentsManifest}
      {resolver}
      caretClass={i === activeTree.nodes.length - 1 ? caretClass : null}
      {renderData}
    />
  {/each}
</div>

// packages/comark-angular/src/components/markdown-parsed.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Type,
  inject,
  type OnInit,
  type OnDestroy,
} from '@angular/core'
import type { ComarkElement, ComarkNode, ComarkTree, NodeRenderData } from 'comark'
import { MarkdownNode } from './markdown-node.component.ts'
import { findLastTextNodeAndAppendNode, getCaret } from '../utils/caret.ts'
import { warnDeprecated } from '../internal/deprecation.ts'

const EMPTY_TREE: ComarkTree = { nodes: [], frontmatter: {}, meta: {} }

/**
 * MarkdownParsed component
 *
 * Renders an already-parsed Comark tree to Angular components/HTML — no
 * parser in the client bundle. Supports custom component mapping for
 * element tags.
 *
 * @example
 * ```html
 * <comark-markdown-parsed [value]="document" [components]="customComponents" />
 * ```
 */
@Component({
  selector: 'comark-markdown-parsed',
  standalone: true,
  imports: [MarkdownNode],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="comark-content">
      @for (node of renderedNodes; track $index) {
        <comark-markdown-node
          [node]="node"
          [components]="components"
          [renderData]="renderData"
        />
      }
    </div>
  `,
})
export class MarkdownParsed implements OnInit, OnDestroy {
  /** The parsed Comark tree to render */
  @Input() value?: ComarkTree

  /**
   * The parsed Comark tree to render
   * @deprecated Use `value` instead
   */
  @Input() tree?: ComarkTree

  /** Custom component mappings for element tags */
  @Input() components: Record<string, Type<any>> = {}

  /** Enable streaming mode */
  @Input() streaming: boolean = false

  /** Append a caret to the last text node (for streaming UIs) */
  @Input() caret: boolean | { class: string } = false

  /** Additional data to pass to the renderer for :binding resolution */
  @Input() data: Record<string, unknown> = {}

  /**
   * Document key used to subscribe to live updates via `globalThis.comarkContext`.
   * Falls back to the tree's own `meta.key` when set by a plugin.
   */
  @Input() comarkKey?: string

  private cdr = inject(ChangeDetectorRef)
  private liveTree: ComarkTree | null = null
  private cleanup?: (clear?: boolean) => void

  private get inputTree(): ComarkTree {
    return this.value ?? this.tree ?? EMPTY_TREE
  }

  // Live document support: if an ambient context exists, subscribe to updates
  // for this key and re-render with the pushed tree. Cleaned up on destroy.
  ngOnInit(): void {
    if (this.tree !== undefined && this.value === undefined) {
      warnDeprecated('tree (input)', 'value')
    }
    const key = this.inputTree.meta?.key || this.comarkKey
    if (key && globalThis.comarkContext) {
      this.cleanup = globalThis.comarkContext.get(key, this.inputTree).listen((tree) => {
        this.liveTree = tree
        this.cdr.markForCheck()
      })
    }
  }

  ngOnDestroy(): void {
    this.cleanup?.(true)
  }

  private get activeTree(): ComarkTree {
    return this.liveTree ?? this.inputTree
  }

  get renderedNodes(): ComarkNode[] {
    const nodes = [...(this.activeTree.nodes || [])]
    const caretNode = getCaret(this.caret)

    if (this.streaming && caretNode && nodes.length > 0) {
      const hasStreamCaret = findLastTextNodeAndAppendNode(nodes[nodes.length - 1] as ComarkElement, caretNode)
      if (!hasStreamCaret) {
        nodes.push(caretNode)
      }
    }

    return nodes
  }

  get renderData(): NodeRenderData {
    return {
      frontmatter: this.activeTree.frontmatter,
      meta: this.activeTree.meta,
      data: this.data || {},
      props: {},
    }
  }
}

/**
 * @deprecated Use `MarkdownParsed` instead — same component, renamed to
 * describe what it renders. `ComarkRendererComponent` (selector
 * `comark-renderer`) will be removed in a future major version.
 */
@Component({
  selector: 'comark-renderer',
  standalone: true,
  imports: [MarkdownNode],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="comark-content">
      @for (node of renderedNodes; track $index) {
        <comark-markdown-node
          [node]="node"
          [components]="components"
          [renderData]="renderData"
        />
      }
    </div>
  `,
})
export class ComarkRendererComponent extends MarkdownParsed {
  override ngOnInit(): void {
    warnDeprecated('ComarkRendererComponent (<comark-renderer>)', 'MarkdownParsed (<comark-markdown-parsed>)')
    super.ngOnInit()
  }
}
