// packages/comark-svelte/src/components/MarkdownDocument.svelte
<!--
@component
Renders an already-parsed Markdown document to Svelte components/HTML — no
parser in the client bundle.

Accepts a parsed `MarkdownDocument` and renders each top-level node via `MarkdownNode`.
Supports custom component mappings and a streaming caret indicator.

@example
```svelte
<script>
  import { MarkdownDocument } from '@comark/svelte'
  import { parseMarkdown } from 'comark'

  const document = await parseMarkdown('# Hello **World**')
</script>

<MarkdownDocument value={document} />
```
-->
<script lang="ts">
  import { untrack } from 'svelte'
  import type { MarkdownDocument as MarkdownDocumentType, ComponentManifest } from 'comark'
  import type { ComponentResolver } from '../types.js'
  import { resolveFilterRegistry } from 'comark/utils'
  import type { BindingFilters } from 'comark/utils'
  import MarkdownNode from './MarkdownNode.svelte'

  let {
    value,
    components = {},
    componentsManifest,
    resolver,
    streaming = false,
    caret: caretProp = false,
    data,
    filters = undefined,
    class: className = '',
    documentKey,
  }: {
    value?: MarkdownDocumentType | { nodes: MarkdownDocumentType['nodes'] }
    components?: Record<string, any>
    componentsManifest?: ComponentManifest
    resolver?: ComponentResolver
    streaming?: boolean
    caret?: boolean | { class: string }
    data?: Record<string, unknown>
    filters?: BindingFilters
    class?: string
    documentKey?: string
  } = $props()

  let document = $derived(value ?? { nodes: [] })

  // Live document support: if an ambient context exists, subscribe to updates
  // for this key and re-render with the pushed document. Cleaned up on unmount.
  // The key is the document's own `meta.key` (set by a plugin) or the `documentKey` prop.
  let liveDocument = $state<MarkdownDocumentType | null>(null)
  let key = $derived((document as MarkdownDocumentType).meta?.key || documentKey)
  $effect(() => {
    if (!key || !globalThis.comarkContext) return
    const seed = untrack(() => document as MarkdownDocumentType)
    const cleanup = globalThis.comarkContext.get(key, seed).listen((next) => (liveDocument = next))
    return () => cleanup(true)
  })

  let activeDocument = $derived(liveDocument ?? document)

  let caretClass = $derived(
    streaming && caretProp
      ? (typeof caretProp === 'object' && caretProp.class) || ''
      : null,
  )

  let resolvedFilters = $derived(resolveFilterRegistry(filters))

  let renderData = $derived({
    frontmatter:
      (activeDocument as MarkdownDocumentType).frontmatter ||
      (activeDocument as unknown as { data: Record<string, unknown> }).data ||
      {},
    meta: (activeDocument as MarkdownDocumentType).meta || {},
    data: data || {},
    props: {},
  })
</script>

<div class="comark-content {className}">
  {#each activeDocument.nodes as node, i (i)}
    <MarkdownNode
      {node}
      {components}
      {componentsManifest}
      {resolver}
      caretClass={i === activeDocument.nodes.length - 1 ? caretClass : null}
      {renderData}
      filters={resolvedFilters}
    />
  {/each}
</div>

// packages/comark-angular/src/components/markdown-document.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Type,
  inject,
  type OnInit,
  type OnDestroy,
} from '@angular/core'
import type { ElementNode, Node, MarkdownDocument as MarkdownDocumentType, NodeRenderData } from 'comark'
import { resolveFilterRegistry } from 'comark/utils'
import type { BindingFilters } from 'comark/utils'
import { MarkdownNode } from './markdown-node.component.ts'
import { findLastTextNodeAndAppendNode, getCaret } from '../utils/caret.ts'

const EMPTY_DOCUMENT: MarkdownDocumentType = { nodes: [], frontmatter: {}, meta: {} }

/**
 * MarkdownDocument component
 *
 * Renders an already-parsed Markdown document to Angular components/HTML — no
 * parser in the client bundle. Supports custom component mapping for
 * element tags.
 *
 * @example
 * ```html
 * <comark-markdown-document [value]="document" [components]="customComponents" />
 * ```
 */
@Component({
  selector: 'comark-markdown-document',
  standalone: true,
  imports: [MarkdownNode],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="comark-content">
      @for (node of renderedNodes; track $index) {
        <comark-markdown-node
          [node]="node"
          [components]="components"
          [renderData]="renderData"
          [filters]="resolvedFilters"
        />
      }
    </div>
  `,
})
export class MarkdownDocument implements OnInit, OnDestroy {
  /** The parsed Markdown document to render */
  @Input() value?: MarkdownDocumentType

  /** Custom component mappings for element tags */
  @Input() components: Record<string, Type<any>> = {}

  /** Enable streaming mode */
  @Input() streaming: boolean = false

  /** Append a caret to the last text node (for streaming UIs) */
  @Input() caret: boolean | { class: string } = false

  /** Additional data to pass to the renderer for :binding resolution */
  @Input() data: Record<string, unknown> = {}

  /** Named filter functions for pipe-filter expressions */
  @Input() filters: BindingFilters = {}

  /**
   * Document key used to subscribe to live updates via `globalThis.comarkContext`.
   * Falls back to the document's own `meta.key` when set by a plugin.
   */
  @Input() documentKey?: string

  private cdr = inject(ChangeDetectorRef)
  private liveDocument: MarkdownDocumentType | null = null
  private cleanup?: (clear?: boolean) => void

  private get inputDocument(): MarkdownDocumentType {
    return this.value ?? EMPTY_DOCUMENT
  }

  // Live document support: if an ambient context exists, subscribe to updates
  // for this key and re-render with the pushed document. Cleaned up on destroy.
  ngOnInit(): void {
    const key = this.inputDocument.meta?.key || this.documentKey
    if (key && globalThis.comarkContext) {
      this.cleanup = globalThis.comarkContext.get(key, this.inputDocument).listen((document) => {
        this.liveDocument = document
        this.cdr.markForCheck()
      })
    }
  }

  ngOnDestroy(): void {
    this.cleanup?.(true)
  }

  private get activeDocument(): MarkdownDocumentType {
    return this.liveDocument ?? this.inputDocument
  }

  get renderedNodes(): Node[] {
    const nodes = [...(this.activeDocument.nodes || [])]
    const caretNode = getCaret(this.caret)

    if (this.streaming && caretNode && nodes.length > 0) {
      const hasStreamCaret = findLastTextNodeAndAppendNode(nodes[nodes.length - 1] as ElementNode, caretNode)
      if (!hasStreamCaret) {
        nodes.push(caretNode)
      }
    }

    return nodes
  }

  get renderData(): NodeRenderData {
    return {
      frontmatter: this.activeDocument.frontmatter,
      meta: this.activeDocument.meta,
      data: this.data || {},
      props: {},
    }
  }

  get resolvedFilters(): BindingFilters {
    return resolveFilterRegistry(this.filters)
  }
}
