// examples/2.vite/react/src/pages/BlogPost.tsx
import { useEffect, useState } from 'react'
import { MarkdownParsed } from '@comark/react'
import { getPost, type Post } from '../lib/posts'
import Alert from '../components/Alert'
import { Link } from '../router'

function formatDate(date: string): string {
  return new Date(date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

export default function BlogPost({ slug }: { slug: string }) {
  const [post, setPost] = useState<Post | null>(null)

  useEffect(() => {
    getPost(slug).then(setPost)
  }, [slug])

  if (!post) return null

  return (
    <article>
      <header className="pb-4 mb-8 not-prose">
        <Link
          to="/"
          className="text-sm text-neutral-500 dark:text-neutral-400 hover:text-neutral-700 dark:hover:text-neutral-300 mb-4 inline-block no-underline"
        >
          &larr; Back to all posts
        </Link>
        <h1 className="text-3xl font-bold mb-2">{post.title}</h1>
        <div className="flex items-center gap-3 text-sm text-neutral-500 dark:text-neutral-400">
          <time dateTime={post.pubDate}>{formatDate(post.pubDate)}</time>
          <div className="flex gap-1.5">
            {post.tags.map((tag) => (
              <span
                key={tag}
                className="px-1.5 py-0.5 rounded text-xs bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
      </header>
      <MarkdownParsed
        value={post.tree}
        components={{ Alert }}
      />
    </article>
  )
}

// examples/2.vite/angular/src/app/pages/blog-post.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core'
import { ActivatedRoute, RouterLink } from '@angular/router'
import { MarkdownParsed } from '@comark/angular'
import { getPost, type Post } from '../lib/posts'
import { AlertComponent } from '../components/alert.component'

@Component({
  selector: 'app-blog-post',
  standalone: true,
  imports: [MarkdownParsed, RouterLink],
  template: `
    @if (post) {
      <article>
        <header class="pb-4 mb-8">
          <a
            routerLink="/"
            class="text-sm text-neutral-500 dark:text-neutral-400 hover:text-neutral-700 dark:hover:text-neutral-300 mb-4 inline-block no-underline cursor-pointer"
          >
            &larr; Back to all posts
          </a>
          <h1 class="text-3xl font-bold mb-2">{{ post.title }}</h1>
          <div class="flex items-center gap-3 text-sm text-neutral-500 dark:text-neutral-400">
            <time [attr.datetime]="post.pubDate">
              {{ formatDate(post.pubDate) }}
            </time>
            <div class="flex gap-1.5">
              @for (tag of post.tags; track tag) {
                <span
                  class="px-1.5 py-0.5 rounded text-xs bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400"
                >
                  {{ tag }}
                </span>
              }
            </div>
          </div>
        </header>
        <comark-markdown-parsed
          [value]="post.tree"
          [components]="components"
        />
      </article>
    }
  `,
})
export class BlogPostComponent implements OnInit {
  post: Post | null = null
  components = { alert: AlertComponent }

  constructor(
    private route: ActivatedRoute,
    private cdr: ChangeDetectorRef
  ) {}

  async ngOnInit() {
    this.route.params.subscribe(async (params) => {
      const slug = params['slug']
      if (slug) {
        this.post = await getPost(slug)
        this.cdr.detectChanges()
      }
    })
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
  }
}
