// packages/comark/src/react/components/Comark.tsx
import React, { useState, useEffect } from 'react'
import { parse } from '../../index'
import type { ComarkTree } from '../../ast/types'
import type { ParseOptions } from '../../types'
import { ComarkRenderer } from './ComarkRenderer'

export interface ComarkProps {
  /**
   * The children content to parse and render
   */
  children?: React.ReactNode

  /**
   * The markdown content to parse and render
   */
  markdown?: string

  /**
   * Parser options
   */
  options?: ParseOptions

  /**
   * Custom component mappings for element tags
   * Key: tag name (e.g., 'h1', 'p', 'MyComponent')
   * Value: React component
   */
  components?: Record<string, React.ComponentType<any>>

  /**
   * Dynamic component resolver function
   * Used to resolve components that aren't in the components map
   */
  componentsManifest?: (name: string) => Promise<{ default: React.ComponentType<any> }>

  /**
   * Enable streaming mode with enhanced components (e.g., ShikiCodeBlock)
   */
  streaming?: boolean

  /**
   * Additional className for the wrapper div
   */
  className?: string
}

/**
 * Comark component
 *
 * High-level component that accepts markdown as a string prop,
 * parses it, and renders it using ComarkRenderer.
 *
 * @example
 * ```tsx
 * import { Comark } from 'comark/react'
 * import CustomHeading from './CustomHeading'
 *
 * const customComponents = {
 *   h1: CustomHeading,
 *   alert: AlertComponent,
 * }
 *
 * export default function App() {
 *   const content = `
 *     # Hello World
 *
 *     This is a **markdown** document with *Comark* components.
 *
 *     ::alert{type="info"}
 *     This is an alert component
 *     ::
 *   `
 *
 *   return <Comark markdown={content} components={customComponents} />
 * }
 * ```
 */
export const Comark: React.FC<ComarkProps> = ({
  children,
  markdown = '',
  options = {},
  components: customComponents = {},
  componentsManifest,
  streaming = false,
  className,
}) => {
  const [parsed, setParsed] = useState<ComarkTree | null>(null)

  // Parse the markdown content
  useEffect(() => {
    let isMounted = true

    // Use async parse for non-streaming mode (supports code highlighting, etc.)
    parse(children ? String(children) : markdown, options).then((result) => {
      if (isMounted) {
        setParsed(result)
      }
    }).catch((error) => {
      console.error('Failed to parse markdown:', error)
    })

    return () => {
      isMounted = false
    }
  }, [markdown, children, streaming])

  if (!parsed) {
    return null
  }

  return (
    <ComarkRenderer
      tree={parsed}
      components={customComponents}
      componentsManifest={componentsManifest}
      streaming={streaming}
      className={className}
    />
  )
}

// packages/comark-svelte/src/Comark.svelte
<!--
@component
High-level Comark component that accepts a markdown string, parses it, and renders it.

Uses `$state` and `$effect` for async parsing — no experimental features required.
Renders nothing until the first parse completes.

@example
```svelte
<script>
  import { Comark } from '@comark/svelte'
  import Alert from './Alert.svelte'

  let content = `
# Hello World

::alert{type="info"}
This is an alert component
::
`
</script>

<Comark markdown={content} components={{ alert: Alert }} />
```
-->
<script lang="ts">
  import type { ComarkTree } from 'comark/ast'
  import type { ComarkPlugin, ComponentManifest } from 'comark'
  import { parse } from 'comark'
  import ComarkRenderer from './ComarkRenderer.svelte'

  let {
    markdown = '',
    options = {},
    plugins = [],
    components = {},
    componentsManifest,
    streaming = false,
    caret = false,
    class: className = '',
  }: {
    markdown?: string
    options?: Record<string, any>
    plugins?: ComarkPlugin[]
    components?: Record<string, any>
    componentsManifest?: ComponentManifest
    streaming?: boolean
    caret?: boolean | { class: string }
    class?: string
  } = $props()

  let parsed: ComarkTree | null = $state(null)

  let content = $derived((markdown || '').trim())

  $effect(() => {
    parse(content, { ...options, plugins }).then((result) => {
      parsed = result
    })
  })
</script>

{#if parsed}
  <ComarkRenderer tree={parsed} {components} {componentsManifest} {streaming} {caret} class={className} />
{/if}
